kind: pipeline
type: docker
name: DouShouKi_malanone

trigger:
    event:
        - push

steps:
  - name: build-model
    image: swift:latest
    commands:
        - cd Model
        - swift build

  - name: build-extension
    image: swift:latest
    commands:
        - cd Extensions
        - swift build

  - name: test
    image: swift:latest
    commands:
        - cd Model
        - swift test